- name: Disable sshd with password and remove 50-cloud-init.conf
  hosts: all
  become: true
  tasks:
      - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/var/lib/awx/projects/nvme/ssh-tunnel-private.pub') }}"
