- name: Update .bashrc file
  hosts: all
  become: yes
  tasks:
    - name: Ensure .bashrc exists
      ansible.builtin.file:
        path: /root/.bashrc
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Add content to .bashrc if not already present
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: 'export PS1="\[\e[34m\][\[\e[m\]\[\e[35m\]\u\[\e[m\]\[\e[31m\]@\[\e[m\]\[\e[33m\]\h\[\e[m\]:\[\e[32m\]\w\[\e[m\]\[\e[34m\]]\[\e[m\]\[\e[37;41m\]\\$\[\e[m\] "'
        state: present
        create: yes
