- name: Playbook ceph host first configure
  hosts: all
  become: yes
  tasks:
# 1. Add bashrc content  
    - name: Ensure .bashrc exists
      ansible.builtin.file:
        path: /root/.bashrc
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Add content to .bashrc if not already present
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        line: 'export PS1="\[\e[34m\][\[\e[m\]\[\e[35m\]\u\[\e[m\]\[\e[31m\]@\[\e[m\]\[\e[33m\]\h\[\e[m\]:\[\e[32m\]\w\[\e[m\]\[\e[34m\]]\[\e[m\]\[\e[37;41m\]\\$\[\e[m\] "'
        state: present
        create: yes
# 2. Add hosts file
    - name: Add multiple entries to /etc/hosts
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: "#CEPH-HOST"
        block: |
          172.240.10.50   hcm01-cloudst-nvme01.fpt.net
          172.240.10.51   hcm01-cloudst-nvme02.fpt.net
          172.240.10.52   hcm01-cloudst-nvme03.fpt.net
          172.240.10.53   hcm01-cloudst-nvme04.fpt.net
          172.240.10.54   hcm01-cloudst-nvme05.fpt.net
          172.240.10.55   hcm01-cloudst-nvme06.fpt.net
# 3. Add kernel custom
    - name: Insert kernel tuning parameters
      ansible.builtin.blockinfile:
        path: /etc/sysctl.conf
        block: |
          #Custom kernel parameters
          net.netfilter.nf_conntrack_tcp_timeout_established = 600
          net.nf_conntrack_max = 1048576
          net.netfilter.nf_conntrack_max = 1048576
          kernel.pid_max = 4194303
          kernel.threads-max = 2097152
          vm.max_map_count = 524288
          vm.min_free_kbytes = 2097152
          vm.vfs_cache_pressure = 10
          vm.zone_reclaim_mode = 0
          vm.dirty_ratio = 80
          vm.dirty_background_ratio = 3
          net.ipv4.tcp_timestamps = 0
          net.ipv4.tcp_sack = 1
          net.core.netdev_max_backlog = 250000
          net.ipv4.tcp_max_syn_backlog = 100000
          net.ipv4.tcp_max_tw_buckets = 2000000
          net.ipv4.tcp_tw_reuse = 1
          net.core.rmem_max = 2147483647
          net.core.wmem_max = 2147483647
          net.core.rmem_default = 4194304
          net.core.wmem_default = 4194304
          net.ipv4.tcp_window_scaling = 1
          net.ipv4.tcp_fin_timeout = 15
          net.ipv4.tcp_keepalive_intvl = 30
          net.ipv4.tcp_moderate_rcvbuf = 1
          net.ipv4.tcp_mem = 2147483647
          net.core.optmem_max = 4194304
          net.ipv4.tcp_rmem = 10240 87380 2147483647
          net.ipv4.tcp_wmem = 10240 87380 2147483647
          net.ipv4.tcp_low_latency = 1
          net.ipv4.tcp_adv_win_scale = 1
          net.ipv4.tcp_slow_start_after_idle = 0
          net.ipv4.tcp_no_metrics_save = 1
          net.ipv4.tcp_syncookies = 0
          net.core.somaxconn = 3240000
          net.ipv4.tcp_max_syn_backlog = 3240000
          net.ipv4.tcp_ecn = 0
          net.ipv4.conf.all.send_redirects = 0
          net.ipv4.conf.all.accept_source_route = 0
          net.ipv4.icmp_echo_ignore_broadcasts = 1
          net.ipv4.tcp_no_metrics_save = 1
          net.ipv4.tcp_slow_start_after_idle = 0
          net.netfilter.nf_conntrack_max = 1524288
          net.nf_conntrack_max = 1524288
          fs.file-max = 1000000
          net.netfilter.nf_conntrack_tcp_timeout_established = 600
          net.nf_conntrack_max = 1048576
          net.netfilter.nf_conntrack_max = 1048576
          kernel.pid_max = 4194303
          kernel.threads-max = 2097152
          vm.max_map_count = 524288
          vm.min_free_kbytes = 2097152
          vm.vfs_cache_pressure = 10
          vm.zone_reclaim_mode = 0
          vm.dirty_ratio = 80
          vm.dirty_background_ratio = 3
          net.ipv4.tcp_timestamps = 0
          net.ipv4.tcp_sack = 1
          net.core.netdev_max_backlog = 250000
          net.ipv4.tcp_max_syn_backlog = 100000
          net.ipv4.tcp_max_tw_buckets = 2000000
          net.ipv4.tcp_tw_reuse = 1
          net.core.rmem_max = 2147483647
          net.core.wmem_max = 2147483647
          net.core.rmem_default = 4194304
          net.core.wmem_default = 4194304
          net.ipv4.tcp_window_scaling = 1
          net.ipv4.tcp_fin_timeout = 15
          net.ipv4.tcp_keepalive_intvl = 30
          net.ipv4.tcp_moderate_rcvbuf = 1
          net.ipv4.tcp_mem = 2147483647
          net.core.optmem_max = 4194304
          net.ipv4.tcp_rmem = 10240 87380 2147483647
          net.ipv4.tcp_wmem = 10240 87380 2147483647
          net.ipv4.tcp_low_latency = 1
          net.ipv4.tcp_adv_win_scale = 1
          net.ipv4.tcp_slow_start_after_idle = 0
          net.ipv4.tcp_no_metrics_save = 1
          net.ipv4.tcp_syncookies = 0
          net.core.somaxconn = 3240000
          net.ipv4.tcp_max_syn_backlog = 3240000
          net.ipv4.tcp_ecn = 0
          net.ipv4.conf.all.send_redirects = 0
          net.ipv4.conf.all.accept_source_route = 0
          net.ipv4.icmp_echo_ignore_broadcasts = 1
          net.ipv4.tcp_no_metrics_save = 1
          net.ipv4.tcp_slow_start_after_idle = 0
          net.netfilter.nf_conntrack_max = 1524288
          net.nf_conntrack_max = 1524288
      notify:
        - reload sysctl
  handlers:
    - name: reload sysctl
      ansible.builtin.command: sysctl -p
# 4. Install firewalld
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure firewalld is installed
      ansible.builtin.apt:
        name: firewalld
        state: present
     
    - name: Add source to trusted zone
      ansible.posix.firewalld:
        source: 172.240.10.0/24
        permanent: true
        zone: trusted
        state: enabled
        
    - name: Always reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
# 5. Enable ntp
    - name: Change timezone
        command: timedatectl set-timezone "Asia/Ho_Chi_Minh"
    - name: Set ntp true
        command: timedatectl set-ntp true
    - name: Enable ntp
      ansible.builtin.blockinfile:
         path: /etc/systemd/timesyncd.conf
         block: |
           NTP=172.240.10.10
           FallbackNTP=172.240.10.10
    - name: Restart systemd-timesyncd
      systemd:
          name: systemd-timesyncd
          state: restarted
