- name: Install cepham
  hosts: all
  become: true
  tasks:
    - name: Set +x
      ansible.builtin.command: chmod +x /home/ubuntu/cephadm
      args:
        chdir: /home/ubuntu
    - name: Set owner
      ansible.builtin.command: chown ubuntu:ubuntu /home/ubuntu/cephadm
      args:
        chdir: /home/ubuntu
    - name: Run cephadm add-repo
      ansible.builtin.command: ./cephadm add-repo --release reef
      args:
        chdir: /home/ubuntu
    - name: Install Ceph packages
      ansible.builtin.command: ./cephadm install
      args:
        chdir: /home/ubuntu
      
