- name: Install cepham
  hosts: all
  become: true
  tasks:
    - name: Run cephadm add-repo
      ansible.builtin.command: ./cephadm add-repo --release reef
      args:
        chdir: /home/ubuntu
    - name: Install Ceph packages
      ansible.builtin.command: ./cephadm install
      args:
        chdir: /home/ubuntu
      
