- name: Install firewalld on Ubuntu servers
  hosts: all
  become: true
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure firewalld is installed
      ansible.builtin.apt:
        name: firewalld
        state: present

    - name: Enable and start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started
