- name: Install firewalld on target servers
  hosts: all
  become: true
  tasks:
    - name: Ensure firewalld is installed
      ansible.builtin.yum:
        name: firewalld
        state: present

    - name: Enable and start firewalld service
      ansible.builtin.systemd:
        name: firewalld
        enabled: true
        state: started
