- name: Install and configure Zabbix Agent on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Download Zabbix repository package
      ansible.builtin.get_url:
        url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb"
        dest: "/tmp/zabbix-release_latest_7.0+ubuntu22.04_all.deb"
        mode: '0644'

    - name: Install Zabbix repository package
      ansible.builtin.apt:
        deb: "/tmp/zabbix-release_latest_7.0+ubuntu22.04_all.deb"

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Zabbix Agent
      ansible.builtin.apt:
        name: zabbix-agent
        state: present

    - name: Restart Zabbix Agent service
      ansible.builtin.systemd:
        name: zabbix-agent
        state: restarted

    - name: Enable Zabbix Agent service at boot
      ansible.builtin.systemd:
        name: zabbix-agent
        enabled: yes
