- name: Add multiple sysctl settings
  hosts: all
  become: yes
  tasks:
    - name: Insert kernel tuning parameters
      ansible.builtin.blockinfile:
        path: /etc/sysctl.conf
        block: |
          # Custom kernel parameters
          fs.file-max = 1000000
		  net.netfilter.nf_conntrack_tcp_timeout_established = 600
	      net.nf_conntrack_max = 1048576
		  net.netfilter.nf_conntrack_max = 1048576
		  kernel.pid_max = 4194303
		  kernel.threads-max = 2097152
		  vm.max_map_count = 524288
		  vm.min_free_kbytes = 2097152
		  vm.vfs_cache_pressure = 10
		  vm.zone_reclaim_mode = 0
		  vm.dirty_ratio = 80
		  vm.dirty_background_ratio = 3
		  net.ipv4.tcp_timestamps = 0
		  net.ipv4.tcp_sack = 1
		  net.core.netdev_max_backlog = 250000
		  net.ipv4.tcp_max_syn_backlog = 100000
		  net.ipv4.tcp_max_tw_buckets = 2000000
		  net.ipv4.tcp_tw_reuse = 1
		  net.core.rmem_max = 2147483647
		  net.core.wmem_max = 2147483647
		  net.core.rmem_default = 4194304
		  net.core.wmem_default = 4194304
		  net.ipv4.tcp_window_scaling = 1
		  net.ipv4.tcp_fin_timeout = 15
		  net.ipv4.tcp_keepalive_intvl = 30
		  net.ipv4.tcp_moderate_rcvbuf = 1
		  net.ipv4.tcp_mem = 2147483647
		  net.core.optmem_max = 4194304
		  net.ipv4.tcp_rmem = 10240 87380 2147483647
		  net.ipv4.tcp_wmem = 10240 87380 2147483647
		  net.ipv4.tcp_low_latency = 1
		  net.ipv4.tcp_adv_win_scale = 1
		  net.ipv4.tcp_slow_start_after_idle = 0
		  net.ipv4.tcp_no_metrics_save = 1
		  net.ipv4.tcp_syncookies = 0
		  net.core.somaxconn = 3240000
		  net.ipv4.tcp_max_syn_backlog = 3240000
		  net.ipv4.tcp_ecn = 0
		  net.ipv4.conf.all.send_redirects = 0
		  net.ipv4.conf.all.accept_source_route = 0
		  net.ipv4.icmp_echo_ignore_broadcasts = 1
		  net.ipv4.tcp_no_metrics_save = 1
		  net.ipv4.tcp_slow_start_after_idle = 0
		  net.netfilter.nf_conntrack_max = 1524288
		  net.nf_conntrack_max = 1524288
		  fs.file-max = 1000000
		  net.netfilter.nf_conntrack_tcp_timeout_established = 600
		  net.nf_conntrack_max = 1048576
		  net.netfilter.nf_conntrack_max = 1048576
		  kernel.pid_max = 4194303
		  kernel.threads-max = 2097152
		  vm.max_map_count = 524288
		  vm.min_free_kbytes = 2097152
		  vm.vfs_cache_pressure = 10
		  vm.zone_reclaim_mode = 0
		  vm.dirty_ratio = 80
		  vm.dirty_background_ratio = 3
		  net.ipv4.tcp_timestamps = 0
		  net.ipv4.tcp_sack = 1
		  net.core.netdev_max_backlog = 250000
		  net.ipv4.tcp_max_syn_backlog = 100000
		  net.ipv4.tcp_max_tw_buckets = 2000000
		  net.ipv4.tcp_tw_reuse = 1
		  net.core.rmem_max = 2147483647
		  net.core.wmem_max = 2147483647
		  net.core.rmem_default = 4194304
		  net.core.wmem_default = 4194304
		  net.ipv4.tcp_window_scaling = 1
		  net.ipv4.tcp_fin_timeout = 15
		  net.ipv4.tcp_keepalive_intvl = 30
		  net.ipv4.tcp_moderate_rcvbuf = 1
		  net.ipv4.tcp_mem = 2147483647
		  net.core.optmem_max = 4194304
		  net.ipv4.tcp_rmem = 10240 87380 2147483647
		  net.ipv4.tcp_wmem = 10240 87380 2147483647
		  net.ipv4.tcp_low_latency = 1
		  net.ipv4.tcp_adv_win_scale = 1
		  net.ipv4.tcp_slow_start_after_idle = 0
		  net.ipv4.tcp_no_metrics_save = 1
		  net.ipv4.tcp_syncookies = 0
		  net.core.somaxconn = 3240000
		  net.ipv4.tcp_max_syn_backlog = 3240000
		  net.ipv4.tcp_ecn = 0
		  net.ipv4.conf.all.send_redirects = 0
		  net.ipv4.conf.all.accept_source_route = 0
		  net.ipv4.icmp_echo_ignore_broadcasts = 1
		  net.ipv4.tcp_no_metrics_save = 1
		  net.ipv4.tcp_slow_start_after_idle = 0
		  net.netfilter.nf_conntrack_max = 1524288
		  net.nf_conntrack_max = 1524288
      notify:
        - reload sysctl
  handlers:
    - name: reload sysctl
      ansible.builtin.command: sysctl -p
