- name: Remove service in fwd
  hosts: all
  become: true
  tasks:
    - name: Remove service in fwd
      ansible.posix.firewalld:
        zone: public
        service: ssh
        permanent: true
        state: disable
    - name: Always reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
