- name: Enable ntp
  hosts: all
  become: true
  tasks:
      - name: Change timezone
        command: timedatectl set-timezone "Asia/Ho_Chi_Minh"
      - name: Set ntp true
        command: timedatectl set-ntp true
      - name: Enable ntp
        ansible.builtin.blockinfile:
          path: /etc/systemd/timesyncd.conf
          block: |
            NTP=172.240.10.10
            FallbackNTP=172.240.10.10
      - name: Restart systemd-timesyncd
        systemd:
          name: systemd-timesyncd
          state: restarted
