- name: Disable sshd with password and remove 50-cloud-init.conf
  hosts: all
  become: true
  tasks:
    - name: Disable password login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#PubkeyAuthentication yes'
        line: "PubkeyAuthentication yes"
        state: present
      notify:
        - restart ssh
    - name: Disable password login
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#PasswordAuthentication yes'
        line: "PasswordAuthentication no"
        state: present
      notify:
        - restart ssh
    - name: Remove file (delete file ssh config)
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        state: absent
      notify:
        - restart ssh
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '/home/ubuntu/ssh-tunnel-private.pub') }}"
  handlers:
    - name: restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted
